### ISSUE TITLE
命令

### ISSUE THREAD

**Issue by CaveNightingale** [ElaBosak233/Valkyrie#11]
https://github.com/ElaBosak233/Valkyrie/blob/master/source/Part03/3.1-%E5%91%BD%E4%BB%A4.md
tp的第一个参数不是玩家名而是实体列表（玩家名，实体选择器，实体UUID）
不要用Bukkit思维去理解原版命令，原版/Mod的命令和Bukkit命令很不一样，
还有，你那判断args.length == 0就完了吗？
/hello uuid 23yei82ydud 213eugwd swhuiehduwq
你也照样执行/hello uuid吗？

**Comment by ElaBosak233** [comment]
第一个问题已修改，第二个问题已添加 info 引用框

?> 解决冗余的参数，如果玩家输入了 `/hello uuid 23yei82ydud 213eugwd swhuiehduwq`，照理来说，我们要看的参数是 `23yei82ydud`，后面的将被忽略，但是我们也需要给玩家一个合理的答复，就可以判断 `args.length > 某个整数`，如果为 `true`，则向玩家返回相应的消息
