### ISSUE TITLE
大驼峰命名这个地方

### ISSUE THREAD

**Issue by CaveNightingale** [ElaBosak233/Valkyrie#12]
https://github.com/ElaBosak233/Valkyrie/blame/master/source/Part02/2.2-Java%E4%BB%A3%E7%A0%81%E8%A7%84%E7%BA%A6.md
Java属性名习惯上使用小驼峰
命名空间不得出现大写字母！！否则会出现不识别等问题，因此大驼峰命名空间一定是非法命名空间
而且命名空间属于Minecraft内容而非Java内容
以下内容来自MCWiki
```
命名空间和名称只能包含以下字符：

    0123456789 数字
    abcdefghijklmnopqrstuvwxyz 小写字母
    _ 下划线
    - 连字符号
命名空间和名称的最好命名方法是小写单词加下划线。 
```

**Comment by ElaBosak233** [comment]
已解决！
