### ISSUE TITLE
第三章中的文章错误

### ISSUE THREAD

**Issue by Shiyu-666** [ElaBosak233/Valkyrie#15]
具体位置在“https://valkyrie.ela.ac.cn/#/./source/Part03/3.4-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6?id=%e9%bb%98%e8%ae%a4%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6”
中“我们在 config.yml 中添加一个键，希望用来记录玩家放置方块的总数，既然要监听破坏方块，那么我们创建一个监听器类 BlockPlace.java，在每次写入数据之前，我们得先判断，key 下面是否有对应的值，并且，我们需要获取它的值，如果没有，那么就将它定义为 0，然后我们再向其中写入值，玩家每放置一个方块，那么 score 就会 +1，当然，这些都完成后，千万不能忘记保存 config.yml，否则你做的一切，可能就没了！”我们要监听的是玩家的放置方块而教程却写成了“监听破坏方块”

**Comment by ElaBosak233** [comment]
感谢提醒，已修改
