### ISSUE TITLE
valkyrie中信息出错

### ISSUE THREAD

**Issue by Shiyu-666** [ElaBosak233/Valkyrie#18]
在valkyrie4.4ItemMeta与子类一章中讲到了“屠龙宝刀”的示例，在代码中的注释似乎有一点问题
`ItemStack dragonSword = new ItemStack(Material.GOLDEN_SWORD);
ItemMeta dragonSwordMeta = dragonSword.getItemMeta(); // 从普通的金剑中获取它的 ItemMeta

dragonSwordMeta.setDisplayName(ChatColor.DARK_PURPLE+"屠龙宝刀");  // 设置 屠龙宝刀 的名字

ArrayList<String> lore = new ArrayList<String>();
lore.add(ChatColor.RED+"一刀 999 级");
lore.add(ChatColor.GREEN+"大家好，我系渣渣灰");
dragonSwordMeta.setLore(lore); // 设置 屠龙宝刀 的 lore

dragonSwordMeta.addEnchant(Enchantment.DAMAGE_ALL, 999, true); // 设置 屠龙宝刀 的附魔，第一个是附魔类型，第二个是等级，第三个是忽略等级限制

dragonSword.setItemMeta(dragonSwordMeta); // 将 goldenSword 设置成 屠龙宝刀 的 ItemMeta，后面只需要把这个 goldenSword给玩家就行了
`
最后一行应该是dragonSword才对

**Comment by ElaBosak233** [comment]
感谢提醒，现在（包括后续 10 天的早晨一直到晚上 7 点）我都在外面，回头就立刻更正

**Comment by ElaBosak233** [comment]
已改正
