### ISSUE TITLE
多线程与高并发

### ISSUE THREAD

**Issue by CaveNightingale** [ElaBosak233/Valkyrie#7]
https://github.com/ElaBosak233/Valkyrie/blob/master/source/Part04/4.2-%E5%A4%9A%E7%BA%BF%E7%A8%8B%E4%B8%8E%E9%AB%98%E5%B9%B6%E5%8F%91.md
你不可以@Override一个静态方法！
```
new BukkitRunnable() {
    @Override
    public static void run() {
        ...
        this.cancel(); // 当你的任务运行完毕后，不要忘了关闭这个任务
    }
}.runTask(plugin)
```

**Comment by ElaBosak233** [comment]
已改正，这里我是手误打上去的
